image: node:10.15.3

pipelines:
  branches:
    main:
      - step:
          caches:
            - node
          script: # Modify the commands below to build your repository.
            - apt-get update && apt-get install -y rsync
            - ssh-keyscan -H $SSH_SERVER_IP >> ~/.ssh/known_hosts
            - cd $BITBUCKET_CLONE_DIR
            - rsync -r -v -e ssh . $SSH_SERVER_USER@$SSH_SERVER_IP:/node-assignment --delete-before --exclude '.git'
            - ssh $SSH_SERVER_USER@$SSH_SERVER_IP 'cd /node-assignment && npm install'
            - ssh $SSH_SERVER_USER@$SSH_SERVER_IP 'cd /node-assignment && npm run stop && npm run build && npm run pm2'
