# Push artifacts to ec2 destination using rsync

image: node:10.15.3

pipelines:
  default:
    - step:
        name: Deploy artifacts using rsync to $SSH_SERVER_IP instance
        script:
          - pipe: atlassian/rsync-deploy:0.3.2
            variables:
              USER: $SSH_SERVER_USER
              SERVER: $SSH_SERVER_IP
              REMOTE_PATH: '${REMOTE_DESTINATION_PATH}'
              LOCAL_PATH: '${BITBUCKET_CLONE_DIR}/'
              EXTRA_ARGS: '--exclude=.bitbucket/ --exclude=.git/ --exclude=bitbucket-pipelines.yml --exclude=.gitignore'
          - echo "Deployment is done...!"
